Bypass PIE security
If you're running the Android "L" developer preview image, you may have noticed that some of your native binaries no longer execute:

$ ./mxt-app                             
error: only position independent executables (PIE) are supported.

Please add “LOCAL_CFLAGS += -fPIE –pie” and “LOCAL_LDFLAGS += -fPIE –pie” flag.